# Generated by Django 3.0.8 on 2020-08-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salario',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
